### ISSUE TITLE
Dedicated URLs for filters (categories, countries and languages)

### ISSUE THREAD

**Issue by lucpretti** [okfn/network#138]
For both [Project Repository](https://network.okfn.org/project/) and [Global Directory](https://network.okfn.org/specialist/) –

We need to implement the same solution as #28 for categories, countries and languages (available through dropdown menus): filtered content results should generate its own dedicated URL with the parameters of the filter. 

![Screenshot 2023-10-11 at 11 07 06](https://github.com/okfn/network/assets/8523847/42020fc9-27bb-489b-8c1b-34e003723859)

That would give us more flexibility in promoting people and projects publicly, as well as help disseminate targeted content (e.g. all people from one country, or all projects under a given category)

**Comment by amercader** [comment]
Done @lucpretti, (many thanks to @aivuk !)
see eg
https://network.okfn.org/specialist/?language=Belarusian
https://network.okfn.org/project/?category=Open%20Data,Open%20Farming

**Comment by lucpretti** [comment]
Thank you so much @amercader @aivuk!
