### ISSUE TITLE
Metatags missing

### ISSUE THREAD

**Issue by sapetti9** [okfn/network#25]
Both the directory and the repository webpages are missing metatags, which means they will be poorly displayed when shared on social media. For reference:
https://www.opengraph.xyz/url/https%3A%2F%2Fnetwork.okfn.org%2Fproject%2F
https://www.opengraph.xyz/url/https%3A%2F%2Fnetwork.okfn.org%2Fspecialist%2F

**Comment by aivuk** [comment]
Metadata added, but we need a better picture for it

**Comment by aivuk** [comment]
I changed it now to use the same picture as we use on https://okfn.org

**Comment by sapetti9** [comment]
Ok, we should have a distinctive picture for the Repository & the Directory. @onalya can you maybe do that?

**Comment by sapetti9** [comment]
@aivuk can't we just have a page preview?

**Comment by aivuk** [comment]
Just a screenshot of the page? Sure.

**Comment by sapetti9** [comment]
@lucpretti do you have an opinion?

**Comment by onalya** [comment]
I can create a specific metaimage, yes

**Comment by onalya** [comment]
![Metaimage_example](https://user-images.githubusercontent.com/116549808/202202631-d77d7d9f-77d7-406a-9506-9757339fa47c.png)
@sapetti9 how would you like something like this?

**Comment by aivuk** [comment]
@onalya is this for the Global Directory (specialists) or Project Repository?

**Comment by sapetti9** [comment]
This is lovely, thanks @onalya! We will need two different ones, for the Repository and the Directory, but I really like this style! Tagging @lucpretti here, who's our comms manager and in charge of harmonising as much as possible our appearance, to see what he thinks too.

**Comment by onalya** [comment]
Thanks, on the landing page there is a link to the Network, instead of the button with ellipsis I'd like to put this pic.

**Comment by lucpretti** [comment]
Thanks for this @onalya! I really like the style, let's definitely keep this vibe! 

I think this version is too colourful/intense tho. Colours are also slightly impairing readability. 

A few suggestions:
- design two versions, one for Repository, one for Directory
- update texts to "Open Knowledge Repository" and "Open Knowledge Directory" (OKFN may sound too cryptic)
- maybe the middle of the image could remain white? then place the circle patterns at sides/corners?
- use the same highlighting style as in the sites: underlining is thicker, covers all letters and extrapolates down the line
- I love the squares/diamonds. Maybe also testing with the ellipsis?
- add OKFN no-text logo white version somewhere - you can find it here https://drive.google.com/drive/folders/11goqc1DjVa9QbvFGztzeSzgYuw-C8MuA

**Comment by onalya** [comment]
Ok thank you, @lucpretti! Do you still need one for the network in the landing page? Can you also share with me again the last prototype of the landing page? I need to better check the highlighting style. Or how did you implement it in the new website exactly?

**Comment by lucpretti** [comment]
@onalya:

_Do you still need one for the network on the landing page?_
what do you mean? are you suggesting replacing the top-right link with a button?

_Can you also share with me again the last prototype of the landing page? I need to better check the highlighting style. Or how did you implement it in the new website exactly?_

These are the links to the live landing pages:
https://network.okfn.org/specialist/
https://network.okfn.org/project/

Here are the current highlighting styles:

![Captura de Tela 2022-11-18 às 16 55 05](https://user-images.githubusercontent.com/8523847/202746755-06c34274-5903-4f98-b7c6-2deb5a3fe0e9.png)

![Captura de Tela 2022-11-18 às 16 55 11](https://user-images.githubusercontent.com/8523847/202746771-0de990fe-f838-4a2e-a21d-24d18f268564.png)

**Comment by lucpretti** [comment]
@aivuk here is new content for the metatada:

> **Directory**
> `title`: Connect with specialists from the Open Knowledge Network 
> `description`: Our directory is indexing members of the open movement in 20+ countries.
> 
> **Repository**
> `title`: Learn more about Open Knowledge projects worldwide
> `description`: Our openness initiatives are generating impact in 20+ countries, and growing.

@sapetti9 happy to hear your thoughts before deploying

**Comment by onalya** [comment]
No, @lucpretti the new homepage of okfn.org, I saw the prototype and I know that there are an image and a text that link to the network and I would like to use the exact same highlighting.

**Comment by sapetti9** [comment]
Thanks @onalya, I like better the versions that say Global Directory & Project Repository. Can we maybe just have the OKF logo bigger, so that the branding is clearer?

**Comment by lucpretti** [comment]
> 

@onalya Here you go. I haven't actually thought a lot about it. Just copied the ellipsis and placed the title inside. My plan is to actually replace it with the cards you're working on.

![Screenshot 2022-11-21 at 16 03 03](https://user-images.githubusercontent.com/8523847/203088092-57b1885e-44a9-4979-9a3d-0250571eae24.png)

**Comment by lucpretti** [comment]
@onalya I really like these three! Thank you! Much clearer with the white bg.

![Screenshot 2022-11-21 at 16 06 07](https://user-images.githubusercontent.com/8523847/203088603-b85fe4d3-9013-4134-b751-e803bd25acc9.png)

On the branding, there's a decision to make: 
- if "Open Knowledge" is not on the title, we need the landscape logo with text (and in a bigger format) (you can find it here: https://drive.google.com/drive/folders/1V05yWWmq202oxO2HoEuVckSEOu0khOm4?usp=share_link)

Can you try it and then @sapetti9 and I make a final decision? 

I confess I'm leaning towards the versions with "Open Knowledge" on the title, having in mind audiences from outside the open movement.

**Comment by lucpretti** [comment]
I believe we already have the final images for metadata - at least I see them o Figma. Pls confirm @onalya, so @aivuk can update it. 

![repository](https://user-images.githubusercontent.com/8523847/203818036-95ec82d1-e9c7-4d5a-b8dc-3117e6ca6467.png)

![directory](https://user-images.githubusercontent.com/8523847/203818026-722b0851-1cb2-4bc3-b2bb-69a730a6faf2.png)

**Comment by aivuk** [comment]
@lucpretti Just updated it

**Comment by onalya** [comment]
Are them the same of my PR? I added them in one of the last commits

**Comment by aivuk** [comment]
yes, I merged your PR to main already
