### ISSUE TITLE
Different color for OKF core team members

### ISSUE THREAD

**Issue by sapetti9** [okfn/network#26]
ATM the OKF core team members of the Directory are in a different blue than the rest of the members, but all members should look the same:

<img width="864" alt="Schermata 2022-11-16 alle 18 58 18" src="https://user-images.githubusercontent.com/74717970/202257347-cd3791af-18bc-4060-ae46-9b5c4e9dff97.png">

This was adopted a temporary solution adopted to solve an issue of OKF core people disappearing with the normal blue filters the other have, but we need to solve the issue.

Maybe changing the format of the photo could help.

Other possible solution: drop the drawings and have photos instead.

**Comment by aivuk** [comment]
I fixed the issue. The problem was that the OKF Team picture had a transparent background. I edit them and changed it to white background.
