### ISSUE TITLE
Dedicated URLs for profile pop-ups

### ISSUE THREAD

**Issue by lucpretti** [okfn/network#28]
It would be nice if each specialist in the directory has their own dedicated URL. That way, it would be easier to promote each one link on social media. Also, specialists would fell proud and could even add the URL to their own profiles.

This is how it's showing today:

![Captura de Tela 2022-11-17 às 15 32 55](https://user-images.githubusercontent.com/8523847/202475088-dd211692-d353-412f-baea-368aa52bde71.png)

This is the ideal URL. Once you access it, it should take you to the network page with that specific pop-up opened.

![Captura de Tela 2022-11-17 às 15 33 07](https://user-images.githubusercontent.com/8523847/202475108-8ed38e3a-54b8-495c-adbf-663657914acb.png)

Is that possible?

**Comment by aivuk** [comment]
It's a bit complicate to have urls like /specialist/specialist-name but it would be easier to have /specialist#specialist-name. The only disadvantage with the # format would be with the SEO.

**Comment by lucpretti** [comment]
Yes, I imagined that. I'm fine with the # format if it's easier. Are we able to change metadata with the # (or at least the image)?

**Comment by aivuk** [comment]
With the #, it's not possible to have different metadata for each individual card, the only way would be to have separate pages for each individual specialist as /specialist/name.

**Comment by aivuk** [comment]
@lucpretti I think I found a way to generate a page for each specialist. What would be the opengraph metadata for each specialist?

**Comment by aivuk** [comment]
and it's done! https://network.okfn.org/specialist/ if you click on a specialist, the url changes, e.g. if you click on Renata Ávila, the url changes to https://network.okfn.org/specialist/renata-avila. If you access the url https://network.okfn.org/specialist/renata-avila the page opens with Renata information open. Closing the box the url goes back to /specialist. I didn't change the metadata yet, but now with how it's working it's easy to do. Just tell me what to write in the metadata.

**Comment by aivuk** [comment]
@lucpretti done! Each specialist has their own metadata now.

**Comment by lucpretti** [comment]
Amazing! Great job @aivuk!

I tested and the `description` is repeating the `title` - at least according to opengraph.xyz.

![Screenshot 2022-11-21 at 16 13 09](https://user-images.githubusercontent.com/8523847/203090267-224e71d9-bdd2-4274-891d-7f997ece99c2.png)

Check it here: https://www.opengraph.xyz/url/https%3A%2F%2Fnetwork.okfn.org%2Fspecialist%2Fsagar-ghimire

**Comment by aivuk** [comment]
Ops, there was little mistake in the code generating the specialists pages and I was using the title in the description. Now it's fixed, check at: https://www.opengraph.xyz/url/https%3A%2F%2Fnetwork.okfn.org%2Fspecialist%2Fsagar-ghimire

**Comment by lucpretti** [comment]
Perfect! Thank you again!
