### ISSUE TITLE
Specialist card

### ISSUE THREAD

**Issue by sapetti9** [okfn/network#38]
The specialist card should also contain the following info (when relevant, not all time, of course):

• Twitter
• GitHub/GitLab
• Personal Website
• LinkedIn
• Email

See Figma:
<img width="632" alt="Schermata 2022-11-28 alle 15 02 05" src="https://user-images.githubusercontent.com/74717970/204296652-07169678-8237-44a9-96a8-4eaaea929c64.png">

Also, currently there is the wrong symbol associated with the email address:

<img width="760" alt="Schermata 2022-11-28 alle 15 00 25" src="https://user-images.githubusercontent.com/74717970/204296750-45605e1c-2293-4254-8570-edcf3ad2b6d9.png">

**Comment by aivuk** [comment]
Fixed the email icon

**Comment by aivuk** [comment]
I did add the new fields to the specialist form and configured our system to accept them. I configured them to not be required. I'm still not showing them on the specialist card and I think we need now a way to show which fields are required in the form.

**Comment by aivuk** [comment]
@sapetti9 important to note, I also added new columns to the csv. It's important to keep the order, we can't change them for now

**Comment by aivuk** [comment]
@sapetti9 I did add the extra info fields, but if an author has all of them filled, the info window gets too big. For now I removed the fixed scrolling, in that way a visitor can scroll up and down to read all the specialist window content.

**Comment by aivuk** [comment]
please check my entry to see the feature in action: https://network.okfn.org/specialist/edgar-zanella-alvarenga
