### ISSUE TITLE
Dedicated URLs for projects in the repository

### ISSUE THREAD

**Issue by lucpretti** [okfn/network#39]
It would be nice to implement the same solution as #28 for the Project Repository. Each URL should take to the site with the relevant pop-up opened. Metatags should follow the same logic as the Directory:

- "Discover" + project title + "at the Open Knowledge Repository" as `title`, e.g. "Discover Frag den Staat at the Open Knowledge Repository"
- the uploaded project logo as `image`
- "Learn more about this and other projects about open data, data literacies, and more." as `description`

That would make much easier to promote links on social media and get traffic to the repository.

**Comment by aivuk** [comment]
@lucpretti I closed because it's done
